environment:
  matrix:
  - nodejs_version: "0.12"
  - nodejs_version: "4.2"
  - nodejs_version: "5.5"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
